### ISSUE TITLE
Improve naming conventions for Folders

### ISSUE THREAD

**Issue by vjFaLk** [indraaani/LPTHW_Exercises#2]
* Folder `Supplementary_Files` should just be `Supplementary Files` or `SupplementaryFiles` 
There are multiple ways you can name your folders. If you follow python conventions they are lower case with underscores i.e `supplementary_files` (snake_case) . If you follow say, C# or Java conventions, you would write this as `SupplementaryFiles`. 

* Currently there are two folders called "Exercise" and "exercise", this leads to confusion

**Comment by indraaani** [comment]
Done, thanks for pointing it out. :)
