### ISSUE TITLE
Better naming conventions for commit messages

### ISSUE THREAD

**Issue by vjFaLk** [indraaani/LPTHW_Exercises#3]
Ref to https://github.com/indraaani/LPTHW_Exercises/commit/f24bdb4022859dc9b6eacae924233c689b7de4a4

Write it as `[wip] commit message` instead of using a pipe. 

Ref to https://github.com/indraaani/LPTHW_Exercises/commit/58fc79439635435a8306ed8f4bb1f2a944349da1

Write it as `[minor] commit message`

**Comment by indraaani** [comment]
Thanks, will take this into account.
